# Site settings
title: demun(대문블로그)
email: hjm01@naver.com
description: Front End Developer, html, css, javascript, jQuery

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site

# categories: /category
permalink: /:categories/:title/

# permalink: /:title/

# # sns 설정
# twitter_username: demunblog
# github_username: demun
# facebook_username: demunblog
# disqus 댓글 플러그인
disqus_shortname: demunblog
disqus_url: "https://demunblog.disqus.com"

#### Author information
# author: demun
author:
  name: demun      ## e.g. wuchong Author name
  twitter: demunblog   ## e.g. jarkwu for https://twitter.com/jarkwu
  github: demun     ## e.g. wuchong for https://github.com/wuchong
  facebook: demunblog  ## e.g. imjark for https://facebook.com/imjark
  google_plus: "118035701709445624959"    ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  # email: simpleyyt@gmail.com      ## e.g. imjark@gmail.com
  # linkedin:   ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
## if you set them, the corresponding  share button will show on the footer


#### Analytics
google_analytics:
  enable: true
  id: UA-74844096-1        ## e.g. UA-46321946-2 your google analytics ID.
  site: auto      ## e.g. wuchong.me your google analytics site or set the value as auto.

# 코드 하이라이트 설정
# 코드 하이라이트 기능중에 GFM를 사용해서 깃헙사이트와 동일하게 보여준다.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


# markdown: kramdown
# highlighter: pygments


# {% highlight ruby %}
# {% endhighlight %}


# 특정 디렉토리나 파일을 변환되지 않도록 제외시킨다. 
# 지킬에서 빌드되지 않도록하는 폴더를 지정한다
# exclude: [.git, .gitignore, .sass-cache, node_modules]
exclude:
  - .sass-cache
  - .git
  - .gitignore
  - node_modules
  - READMD.md


keep_files: [".git", ".svn"]


# 카테고리 설정
# 첫글자를 대문자로 해도 소문자로 빌드됨
# 카테고리는 post 에 sublimetext 이라고 작성하면 빌드후 sublimetext 폴더에 포스트가 생성된다.
# 머릿말에 카테고리를 지정해줘야 한다.
# category_dir: /category


# 인코딩 설정
encoding: utf-8


# sass는 자동으로 지킬에서 변환한다.
# css  폴더에 main.scss 하고 sass  폴더의 파일을 임포트한다.
# 만약 css 폴더없이 sass 를 변환하고 싶다면 grunt 를 이용해야 한다.
# sass
sass:
  sass_dir: _sass
  style: :compressed








