# Site settings
title: demun(대문블로그)
email: hjm01@naver.com
description: Front End Developer,demun,대문,html,css,javascript,jQuery,demunblog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://demun.github.io/" # the base hostname & protocol for your site
twitter_username: demunblog
github_username: demun

# Build settings
markdown: kramdown


# 특정 디렉토리나 파일을 변환되지 않도록 제외시킨다. 
# exclude: [DIR, FILE, ...]


keep_files: [".git", ".svn"]
encoding: "utf-8"







