# Site settings
title: demun(대문블로그)
email: hjm01@naver.com
description: Front End Developer, demun, 대문, demunblog, html, css, javascript, jQuery
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://demun.github.io/" # the base hostname & protocol for your site

# 코드 하이라이트 설정
# 코드 하이라이트 기능중에 GFM를 사용해서 깃헙사이트와 동일하게 보여준다.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge



# 특정 디렉토리나 파일을 변환되지 않도록 제외시킨다. 
# 지킬에서 빌드되지 않도록하는 폴더를 지정한다
exclude: [.git, .gitignore, .sass-cache, node_modules]

keep_files: [".git", ".svn"]


# 카테고리 설정
# 첫글자를 대문자로 해도 소문자로 빌드됨
# 카테고리는 post 에 sublimetext 이라고 작성하면 빌드후 sublimetext 폴더에 포스트가 생성된다.
# 머릿말에 카테고리를 지정해줘야 한다.
category_dir: /category



# sns 설정
# tumblr: "#"
# pinterest: "#"
# instagram: "#"
# twitter: "#"
# facebook: "#"
# youtube: "#"
# vimeo: "#"
twitter_username: demunblog
github_username: demun



# 인코딩 설정
encoding: utf-8


# sass는 자동으로 지킬에서 변환한다.
# css  폴더에 main.scss 하고 sass  폴더의 파일을 임포트한다.
# 만약 css 폴더없이 sass 를 변환하고 싶다면 grunt 를 이용해야 한다.
# 
# 

# 레이아웃
# 현재의 레이아웃은 공통으로 사용되는 header, footer 로 나눈다
# 또다른 방법은 고정폭, 유동폭 레이아웃 파일을 만들고 {{ content }} 만 작성한다.

